### ISSUE TITLE
[Feature request] More Refined Storage

### ISSUE THREAD

**Issue by embeddedt** [warmthdawn/justenoughdrags#1]
Compatibility with [More Refined Storage](https://github.com/tth05/morerefinedstorage) (or vanilla Refined Storage) would be nice for players who prefer not to use AE2.

I would look into adding it myself but I'm afraid it'd take me a while to understand exactly how the mod-specific GUI handling works.

**Comment by warmthdawn** [comment]
Emm, if I remember correctly, this feature was originally supported by refined storage?
Actually, I myself had referenced some of the RS code.

**Comment by embeddedt** [comment]
I am pretty sure the dragging feature is only in 1.16, but I'll double check.

**Comment by warmthdawn** [comment]
Well, It is disabled by raoulvdberge for some issues.
https://github.com/refinedmods/refinedstorage/issues/1905
I'll try to figure out what happed and add supports.

**Comment by warmthdawn** [comment]
Now you can use it in the latest version.
The pattern gird should hold shift (same as ae2)
Closed.
